/**
 * wx 提审包组包器（B0 · spec v1.3 content.platform wx-submission-kit 条目落点）。
 *
 * 产出 export/wx/（可提审微信小游戏包）：
 *   1. tsc -p tsconfig.wx.json（module=commonjs，主包 CJS 树，零打包器依赖）
 *   2. wx/ 骨架（game.json / project.config.json / game.js）+ 开放数据域源
 *   3. tokens.js —— 开放数据域 token 单源生成（自主包编译产物 render/theme.js NEON 表；
 *      「token 引主包同一份变量文件」，生成物带 GENERATED 头，禁手抄）
 *   4. 运行时资产（sfx m4a / bgm 环 / 分享双卡 + 图标；商店截图属提审材料不入包）
 *   5. manifest.json —— 逐件 sha256 + 主包/开放数据域分列体积（预算断言见 scripts/check-wx-bundle-size.mjs）
 */
import { execSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const GAME = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const EXPORT = path.join(GAME, 'export/wx');
const sha256 = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');

// 1) 主包 CJS 树
console.log('[1/5] tsc (module=commonjs) → export/wx/build-wx/');
execSync('node node_modules/typescript/bin/tsc -p tsconfig.wx.json', { cwd: GAME, stdio: 'inherit' });

// 2) 骨架 + 开放数据域
console.log('[2/5] 骨架与开放数据域落包');
mkdirSync(EXPORT, { recursive: true });
for (const f of ['game.json', 'project.config.json', 'game.js']) {
  cpSync(path.join(GAME, 'wx', f), path.join(EXPORT, f));
}
mkdirSync(path.join(EXPORT, 'open-data-context'), { recursive: true });
for (const f of ['index.js', 'rank.js']) {
  cpSync(path.join(GAME, 'wx/open-data-context', f), path.join(EXPORT, 'open-data-context', f));
}

// 3) tokens.js（自主包编译产物生成——单源纪律）
console.log('[3/5] tokens.js 生成（自主包 theme.js NEON 表）');
// 游戏包 package.json type:module 会把编译产物 .js 当 ESM（wx 运行时无此语义）——
// 构建脚本侧用 .cjs 临时副本以 CJS require 读取，产物不落包
const themeCjs = path.join(EXPORT, '.tmp-theme.cjs');
cpSync(path.join(EXPORT, 'build-wx/render/theme.js'), themeCjs);
const theme = createRequire(import.meta.url)(themeCjs);
rmSync(themeCjs);
const tokensSrc =
  `/** GENERATED by tools/build-wx.mjs @ ${new Date().toISOString()} —— 禁手抄/禁编辑。\n` +
  ` *  token 引主包同一份变量文件（src/render/theme.ts NEON 表，编译产物直取）。\n` +
  ` *  spec v1.3 content.platform wx-open-data-rank：子包产物与主包 token 段 sha256 相等由门禁断言。\n` +
  ` */\n` +
  `module.exports = ${JSON.stringify({ NEON: theme.NEON, BLOCK_NEON_CYCLE: theme.BLOCK_NEON_CYCLE }, null, 2)};\n`;
writeFileSync(path.join(EXPORT, 'open-data-context/tokens.js'), tokensSrc);

// 4) 运行时资产
console.log('[4/5] 运行时资产拷贝');
const copyTree = (src, dest) => {
  if (!existsSync(src)) return 0;
  let n = 0;
  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) n += copyTree(s, d);
    else {
      mkdirSync(path.dirname(d), { recursive: true });
      cpSync(s, d);
      n += 1;
    }
  }
  return n;
};
let assetCount = 0;
assetCount += copyTree(path.join(GAME, 'assets/sfx'), path.join(EXPORT, 'assets/sfx'));
assetCount += copyTree(path.join(GAME, 'assets/bgm'), path.join(EXPORT, 'assets/bgm'));
// 平台素材：仅运行时 + devtools 识别件入包（分享双卡 + 图标）；商店截图/排行 UI 属提审材料与参考件，留仓库不入包
for (const f of ['share-card-5x4.png', 'share-timeline-1x1.png', 'icon.png']) {
  const src = path.join(GAME, 'assets/wx', f);
  if (existsSync(src)) {
    mkdirSync(path.join(EXPORT, 'assets/wx'), { recursive: true });
    cpSync(src, path.join(EXPORT, 'assets/wx', f));
    assetCount += 1;
  }
}
console.log(`      资产 ${assetCount} 件（sfx / bgm / 分享双卡 / 图标；商店截图与排行 UI 属提审材料不入包）`);

// 5) manifest.json（逐件 sha256 + 分列体积）
console.log('[5/5] manifest.json（sha256 清单 + 分列体积）');
const walk = (dir, base = '') =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    const rel = base ? `${base}/${e.name}` : e.name;
    return e.isDirectory() ? walk(p, rel) : [{ path: rel, bytes: statSync(p).size, sha256: sha256(p) }];
  });
const files = walk(EXPORT)
  .filter((f) => f.path !== 'manifest.json') // 自指排除：manifest 清单不含自身（自报 hash 必漂移）
  .sort((a, b) => a.path.localeCompare(b.path));
const mainBytes = files.filter((f) => !f.path.startsWith('open-data-context/')).reduce((s, f) => s + f.bytes, 0);
const openDataBytes = files.filter((f) => f.path.startsWith('open-data-context/')).reduce((s, f) => s + f.bytes, 0);
const specExport = JSON.parse(readFileSync(path.join(GAME, '../../.myrd/spec/stack-tower-spec.json'), 'utf8'));
const budgets = specExport.spec.content.platform.budgets;
const manifest = {
  generatedAt: new Date().toISOString(),
  spec: { id: specExport._platform.platformSpecId, version: specExport._platform.version, numericFreeze: specExport.spec.content.platform.numericFreeze },
  budgets,
  sizes: {
    mainBytes,
    openDataBytes,
    mainWithinBudget: mainBytes <= budgets.mainPackageMaxBytes,
    openDataWithinBudget: openDataBytes <= budgets.openDataContextMaxBytes,
  },
  files,
};
writeFileSync(path.join(EXPORT, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

console.log(`[out ] ${EXPORT}`);
console.log(`[size] 主包 ${(mainBytes / 1024).toFixed(1)}KB / 预算 ${(budgets.mainPackageMaxBytes / 1024 / 1024).toFixed(0)}MB —— ${manifest.sizes.mainWithinBudget ? 'PASS' : 'OVER!'}`);
console.log(`[size] 开放数据域 ${(openDataBytes / 1024).toFixed(1)}KB / 预算 ${(budgets.openDataContextMaxBytes / 1024).toFixed(0)}KB —— ${manifest.sizes.openDataWithinBudget ? 'PASS' : 'OVER!'}`);
console.log(`[done] ${files.length} 件落包，manifest 逐件 sha256 就绪`);
if (!manifest.sizes.mainWithinBudget || !manifest.sizes.openDataWithinBudget) process.exit(1);
