/** GENERATED by tools/build-wx.mjs @ 2026-10-09T04:18:43.530Z —— 禁手抄/禁编辑。
 *  token 引主包同一份变量文件（src/render/theme.ts NEON 表，编译产物直取）。
 *  spec v1.3 content.platform wx-open-data-rank：子包产物与主包 token 段 sha256 相等由门禁断言。
 */
module.exports = {
  "NEON": {
    "NIGHT_SKY_TOP": "#0b1026",
    "NIGHT_SKY_BOTTOM": "#0d2b33",
    "BLOCK_NEON_01": "#00e5ff",
    "BLOCK_NEON_02": "#ff2d95",
    "BLOCK_NEON_03": "#ffb300",
    "BLOCK_NEON_04": "#76ff03",
    "BLOCK_NEON_05": "#b388ff",
    "BLOCK_NEON_06": "#ff6d3a",
    "CUT_FACE": "#ffffff",
    "RIPPLE_RING": "#00e5ff",
    "PERFECT_GLOW": "#ffe57f",
    "UI_BTN_PRIMARY": "#00e5ff",
    "UI_PANEL_HUD": "#060c1c",
    "UI_PANEL_HUD_ALPHA": 0.72,
    "UI_ICON_SOUND": "#9be7ff",
    "DEBRIS": "#141c26",
    "HORIZON": "#1b3a4a"
  },
  "BLOCK_NEON_CYCLE": [
    "#00e5ff",
    "#ff2d95",
    "#ffb300",
    "#76ff03",
    "#b388ff",
    "#ff6d3a"
  ]
};
