#!/usr/bin/env node
/**
 * wx-open-data-rank 条目查（spec v1.3 content.platform wx-open-data-rank · check 面）。
 * 验收口径原文：开放数据域不卡「真机看到真实好友分」（B0 判据 = 渲染管线就绪）。
 * 断言：子包落包与挂载 / token 引主包同一份变量文件（子包 tokens ≡ 主包 theme 编译产物，
 * sha256 相等）/ 子包零色值字面量（禁手抄第二份）/ 渲染管线 API 面 / 主包零好友数据落点。
 */
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { readFileSync, existsSync, readdirSync, statSync, writeFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const GAME = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const P = (...s) => path.join(GAME, 'export/wx', ...s);
const failures = [];
const check = (name, cond) => {
  if (cond) console.log(`  PASS  ${name}`);
  else { failures.push(name); console.log(`  FAIL  ${name}`); }
};

const od = (...s) => P('open-data-context', ...s);
check('开放数据域入口落包（index.js）', existsSync(od('index.js')));
check('渲染器落包（rank.js）', existsSync(od('rank.js')));

// token 单源：tokens.js 为 GENERATED，且与主包 theme 编译产物 NEON 深比一致
const tokensSrc = readFileSync(od('tokens.js'), 'utf8');
check('tokens.js 带 GENERATED 头（构建期生成，禁手抄）', tokensSrc.includes('GENERATED by tools/build-wx.mjs'));
const loadCjs = (p) => {
  const tmp = `${p}.tmp-check.cjs`; // type:module 工作区 → 以 .cjs 副本按 CJS 装载
  writeFileSync(tmp, readFileSync(p));
  const mod = createRequire(import.meta.url)(path.resolve(tmp));
  rmSync(tmp);
  return mod;
};
const tokens = loadCjs(od('tokens.js'));
const theme = loadCjs(P('build-wx/render/theme.js'));
const canon = (o) => createHash('sha256').update(JSON.stringify(o, Object.keys(o ?? {}).sort())).digest('hex');
check('子包 token ≡ 主包 NEON 表（sha256 相等）', canon(tokens.NEON) === canon(theme.NEON));
check('子包 token ≡ 主包 BLOCK_NEON_CYCLE（色循环同源）', canon(tokens.BLOCK_NEON_CYCLE) === canon(theme.BLOCK_NEON_CYCLE));

// 子包源零色值字面量（rank.js/index.js 禁第二份常量；tokens.js 生成件除外）
const hexLiteral = /#[0-9a-fA-F]{6}\b/;
const rankSrc = readFileSync(od('rank.js'), 'utf8');
const idxSrc = readFileSync(od('index.js'), 'utf8');
check('rank.js 零色值字面量（token 单源纪律）', !hexLiteral.test(rankSrc));
check('index.js 零色值字面量', !hexLiteral.test(idxSrc));

// 渲染管线 API 面（开放数据域内）
check('sharedCanvas 直绘入口', idxSrc.includes('getSharedCanvas'));
check('好友数据仅来自 wx.getFriendCloudStorage（开放数据域内）', idxSrc.includes('getFriendCloudStorage'));
check('主包消息触发：wx.onMessage（只收指令不收好友数据）', idxSrc.includes('onMessage'));
check('渲染器纯函数导出（module.exports.renderRank）', rankSrc.includes('renderRank'));

// 主包零好友数据落点（红线：好友数据不出开放数据域）
let mainLeak = false;
const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : [p];
  });
for (const f of walk(P())) {
  if (f.includes(`${path.sep}open-data-context${path.sep}`)) continue;
  if (statSync(f).isFile() && /\.(js|json)$/.test(f) && !f.endsWith('manifest.json')) {
    if (/getFriendCloudStorage|KVDataList/.test(readFileSync(f, 'utf8'))) { mainLeak = true; break; }
  }
}
check('主包零好友数据落点（getFriendCloudStorage/KVDataList 不出现）', !mainLeak);
check('渲染兜底：无好友数据时占位渲染（devtools 合成数据口径）', idxSrc.includes('draw()') || rankSrc.includes('暂无好友数据'));

if (failures.length) {
  console.log(`RESULT: FAIL (${11 - failures.length}/11)`);
  process.exit(1);
}
console.log('RESULT: PASS  — 开放数据域 11 项断言全绿（token 单源 + 管线就绪）');
